---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  #vars_files:
    #- files/secrets/credentials.yml
 
  tasks:

    - name: show message
      debug:
        msg: "Hello"

    - name: show message
      debug:
        msg: "How are you ?"

    - name: show message
      debug:
        msg: "Fine, I hope."
    - name: show message
      copy:
        dest: /tmp/resolv.conf
        content: "nameserver is "
   
